### ISSUE TITLE
Failing to cancel maintenance countdown

### ISSUE THREAD

**Issue by dwilson390** [ElieTGM/MaintenanceMode#4]
/mm cancel currently does not cancel a maintenance countdown and an attempt to always results in a 'Maintenance mode is not scheduled to be enabled!' message, regardless of whether a countdown has been started or not.

Additionally a restart during a schedule enter maintenance mode results in the following output, which is most likely related.

    07.08 22:23:10 [Server] SEVERE java.lang.InterruptedException: sleep interrupted 
    07.08 22:23:10 [Server] SEVERE at java.lang.Thread.sleep(Native Method) 
    07.08 22:23:10 [Server] SEVERE at me.ElieTGM.MaintenanceMode.bungee.EnableRunnable.run(EnableRunnable.java:41) 
    07.08 22:23:10 [Server] SEVERE at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) 
    07.08 22:23:10 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    07.08 22:23:10 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    07.08 22:23:10 [Server] SEVERE at java.lang.Thread.run(Thread.java:745)

*Running under BungeeCord*

**Comment by ElieTGM** [comment]
This is being fixed in the next commit.

Thank you.
