### ISSUE TITLE
error when reload server list

### ISSUE THREAD

**Issue by ChimpGamer** [ElieTGM/MaintenanceMode#5]
getting error in console
00:09:26 [SEVERE] javax.imageio.IIOException: Can't read input file!
00:09:26 [SEVERE] 	at javax.imageio.ImageIO.read(ImageIO.java:1301)
00:09:26 [SEVERE] 	at me.ElieTGM.MaintenanceMode.bungee.ServerListener.ping(ServerListener.java:59)
00:09:26 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:09:26 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:09:26 [SEVERE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:09:26 [SEVERE] 	at java.lang.reflect.Method.invoke(Method.java:498)
00:09:26 [SEVERE] 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
00:09:26 [SEVERE] 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
00:09:26 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
00:09:26 [SEVERE] 	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:226)
00:09:26 [SEVERE] 	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:205)
00:09:26 [SEVERE] 	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:236)
00:09:26 [SEVERE] 	at net.md_5.bungee.protocol.packet.StatusRequest.handle(StatusRequest.java:29)
00:09:26 [SEVERE] 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
00:09:26 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
00:09:26 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
00:09:26 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
00:09:26 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:219)
00:09:26 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:616)
00:09:26 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:457)
00:09:26 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:417)
00:09:26 [SEVERE] 	at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:37)
00:09:26 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
00:09:26 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
00:09:26 [SEVERE] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
00:09:26 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
00:09:26 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
00:09:26 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
00:09:26 [SEVERE] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
00:09:26 [SEVERE] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
00:09:26 [SEVERE] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
00:09:26 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
00:09:26 [SEVERE] 	at java.lang.Thread.run(Thread.java:745)

**Comment by ElieTGM** [comment]
Just set the enable server icon method in the config.yml to false.

That should fix the issue :+1:
